<a href="https://colab.research.google.com/github/Shajitha92/regulatory-data-sql-portfolio/blob/main/python/regulatory_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regulatory Data Analysis with Python and pandas

This notebook uses Python and pandas to explore and analyse the regulatory dataset created for my SQL portfolio project.

The analysis includes data inspection, filtering, sorting, grouping, aggregation and date-based analysis.

## 1. Load the dataset

In [1]:
import pandas as pd
df = pd.read_csv("/content/regulatory_documents.csv")
df.head()

,document_id,title,publisher_name,jurisdiction_name,document_type,publication_date,effective_date,status
0,1030,2025 Annual Report,ESMA,European Union,Annual Report,2026-06-17,2026-06-17,Active
1,1017,Key focus areas for 2025 reporting,AFM,Netherlands,Guidance,2025-10-24,NaN,Active
2,1025,SR 25-4: Frequently Asked Questions Regarding ...,Federal Reserve,United States,Supervisory Letter,2025-10-10,NaN,Active
3,1026,OCC Bulletin 2025-31: Bank Secrecy Act/Anti-Mo...,OCC,United States,Bulletin,2025-10-09,NaN,Active
4,1009,Monthly Report - September 2025,Deutsche Bundesbank,Germany,Report,2025-09-18,NaN,Active

In [ ]:
df.columns
df.dtypes
df["publication_date"] = pd.to_datetime(df["publication_date"])
df["effective_date"] = pd.to_datetime(df["effective_date"])
df.dtypes

document_id                   int64
title                        object
publisher_name               object
jurisdiction_name            object
document_type                object
publication_date     datetime64[ns]
effective_date       datetime64[ns]
status                       object
dtype: object

## 2. Inspect the data

In [ ]:
df.columns
df.dtypes

document_id                   int64
title                        object
publisher_name               object
jurisdiction_name            object
document_type                object
publication_date     datetime64[ns]
effective_date       datetime64[ns]
status                       object
dtype: object

In [2]:
df["publication_date"] = pd.to_datetime(df["publication_date"])
df["effective_date"] = pd.to_datetime(df["effective_date"])

df.dtypes

document_id                   int64
title                        object
publisher_name               object
jurisdiction_name            object
document_type                object
publication_date     datetime64[ns]
effective_date       datetime64[ns]
status                       object
dtype: object

## 3. Filter and sort regulatory documents

In [ ]:
filtered_df = df[df["publication_date"] < "2025-01-01"]
print(filtered_df)

    document_id                                              title  \
21         1004          SS3/24: Credit risk definition of default
22         1003  SS2/24: Solvent exit planning for non-systemic...
23         1006  Guidelines on policies and controls for the ef...
24         1007  Guidelines on the use of remote customer onboa...
25         1002  FG22/5: Final non-Handbook guidance for firms ...
26         1005               Guidelines on risk-based supervision
27         1028  Guidelines on the MiFID II/MiFIR obligations o...
28         1008  Guidelines on certain aspects of the MiFID II ...
29         1010                Guide to fit and proper assessments

   publisher_name jurisdiction_name          document_type publication_date  \
21            PRA    United Kingdom  Supervisory Statement       2024-09-12
22            PRA    United Kingdom  Supervisory Statement       2024-03-12
23            EBA    European Union             Guidelines       2023-03-31
24            EBA    European Union             Guidelines       2022-11-22
25            FCA    United Kingdom               Guidance       2022-07-27
26            EBA    European Union             Guidelines       2021-12-16
27           ESMA    European Union             Guidelines       2021-08-18
28           ESMA    European Union             Guidelines       2018-05-03
29            ECB    European Union                  Guide       2018-05-01

   effective_date      status
21     2024-09-12  Superseded
22     2025-10-01      Active
23     2023-11-03      Active
24     2023-10-02      Active
25     2023-07-31      Active
26     2022-07-04      Active
27     2022-01-01   Withdrawn
28     2018-05-03      Active
29     2018-05-01      Active

In [ ]:
print(df[df["publication_date"]>="2025-01-01"])

    document_id                                              title  \
0          1030                                 2025 Annual Report
1          1017                 Key focus areas for 2025 reporting
2          1025  SR 25-4: Frequently Asked Questions Regarding ...
3          1026  OCC Bulletin 2025-31: Bank Secrecy Act/Anti-Mo...
4          1009                    Monthly Report - September 2025
5          1024  Staff Advisory: Registration Framework for For...
6          1029  FDIC Supervisory Approach Regarding the Use of...
7          1014             FG25/5: Primary Market Bulletin No. 57
8          1013  FG25/4: Amendments to PRA Rulebook and FCA Gui...
9          1012   FG25/3: Treatment of politically exposed persons
10         1020  PS8/25: Updates to the UK policy framework for...
11         1021  Circular CSSF 25/893 - Reporting of major ICT-...
12         1015  Instruction No. 2025-I-04 on electronic signat...
13         1022  FINMA Guidance 02/2025 - Risks in the real est...
14         1018    Submission DORA information register - guidance
15         1019  Periodic questionnaire on the prevention of mo...
16         1016     Regulatory and Supervisory Outlook Report 2025
17         1023                      Staff Statement on Meme Coins
18         1001  Circular 02/2025 (A) - Minimum requirements fo...
19         1027  Final report on amending Guidelines on ICT ris...
20         1011     AMF Action and Supervisory Priorities for 2025

             publisher_name jurisdiction_name         document_type  \
0                      ESMA    European Union         Annual Report
1                       AFM       Netherlands              Guidance
2           Federal Reserve     United States    Supervisory Letter
3                       OCC     United States              Bulletin
4       Deutsche Bundesbank           Germany                Report
5                      CFTC     United States              Advisory
6                      FDIC     United States  Supervisory Guidance
7                       FCA    United Kingdom    Finalised Guidance
8                       FCA    United Kingdom    Finalised Guidance
9                       FCA    United Kingdom    Finalised Guidance
10                      PRA    United Kingdom      Policy Statement
11                     CSSF        Luxembourg              Circular
12                     ACPR            France           Instruction
13                    FINMA       Switzerland              Guidance
14    De Nederlandsche Bank       Netherlands              Guidance
15                     FSMA           Belgium              Circular
16  Central Bank of Ireland           Ireland                Report
17                      SEC     United States             Statement
18                    BaFin           Germany              Circular
19                      EBA    European Union          Final Report
20                      AMF            France                Report

   publication_date effective_date      status
0        2026-06-17     2026-06-17      Active
1        2025-10-24            NaT      Active
2        2025-10-10            NaT      Active
3        2025-10-09            NaT      Active
4        2025-09-18            NaT      Active
5        2025-08-28            NaT  Superseded
6        2025-08-05            NaT      Active
7        2025-07-25     2025-07-25      Active
8        2025-07-08     2025-07-08      Active
9        2025-07-07     2025-07-07      Active
10       2025-07-03     2025-07-03      Active
11       2025-05-28            NaT      Active
12       2025-05-22            NaT      Active
13       2025-05-22            NaT      Active
14       2025-04-22            NaT      Active
15       2025-04-01            NaT   Withdrawn
16       2025-02-28            NaT  Superseded
17       2025-02-27            NaT      Active
18       2025-02-12            NaT      Active
19       2025-02-11     2025-02-11      Active
20       2025-01-16            NaT      Active

In [ ]:
recent_df = df[df["publication_date"] >= "2025-01-01"]
print(recent_df[["publisher_name", "title", "publication_date"]])

             publisher_name  \
0                      ESMA
1                       AFM
2           Federal Reserve
3                       OCC
4       Deutsche Bundesbank
5                      CFTC
6                      FDIC
7                       FCA
8                       FCA
9                       FCA
10                      PRA
11                     CSSF
12                     ACPR
13                    FINMA
14    De Nederlandsche Bank
15                     FSMA
16  Central Bank of Ireland
17                      SEC
18                    BaFin
19                      EBA
20                      AMF

                                                title publication_date
0                                  2025 Annual Report       2026-06-17
1                  Key focus areas for 2025 reporting       2025-10-24
2   SR 25-4: Frequently Asked Questions Regarding ...       2025-10-10
3   OCC Bulletin 2025-31: Bank Secrecy Act/Anti-Mo...       2025-10-09
4                     Monthly Report - September 2025       2025-09-18
5   Staff Advisory: Registration Framework for For...       2025-08-28
6   FDIC Supervisory Approach Regarding the Use of...       2025-08-05
7              FG25/5: Primary Market Bulletin No. 57       2025-07-25
8   FG25/4: Amendments to PRA Rulebook and FCA Gui...       2025-07-08
9    FG25/3: Treatment of politically exposed persons       2025-07-07
10  PS8/25: Updates to the UK policy framework for...       2025-07-03
11  Circular CSSF 25/893 - Reporting of major ICT-...       2025-05-28
12  Instruction No. 2025-I-04 on electronic signat...       2025-05-22
13  FINMA Guidance 02/2025 - Risks in the real est...       2025-05-22
14    Submission DORA information register - guidance       2025-04-22
15  Periodic questionnaire on the prevention of mo...       2025-04-01
16     Regulatory and Supervisory Outlook Report 2025       2025-02-28
17                      Staff Statement on Meme Coins       2025-02-27
18  Circular 02/2025 (A) - Minimum requirements fo...       2025-02-12
19  Final report on amending Guidelines on ICT ris...       2025-02-11
20     AMF Action and Supervisory Priorities for 2025       2025-01-16

## 4. Regulatory document analysis by publisher, jurisdiction and status

In [ ]:
temp_1 = (df.groupby("publisher_name")["document_id"].count())
print(temp_1.sort_values(ascending=False))

publisher_name
FCA                        4
EBA                        4
ESMA                       3
PRA                        3
BaFin                      1
AMF                        1
AFM                        1
ACPR                       1
De Nederlandsche Bank      1
Central Bank of Ireland    1
CFTC                       1
CSSF                       1
ECB                        1
Deutsche Bundesbank        1
FINMA                      1
FDIC                       1
FSMA                       1
Federal Reserve            1
OCC                        1
SEC                        1
Name: document_id, dtype: int64

In [ ]:
jurisdiction_counts = df.groupby("jurisdiction_name")["document_id"].count()
print(jurisdiction_counts.sort_values(ascending=False))

jurisdiction_name
European Union    8
United Kingdom    7
United States     5
Netherlands       2
France            2
Germany           2
Belgium           1
Ireland           1
Luxembourg        1
Switzerland       1
Name: document_id, dtype: int64

In [ ]:
status_counts = df.groupby("status")["document_id"].count()
print(status_counts)

status
Active        25
Superseded     3
Withdrawn      2
Name: document_id, dtype: int64

In [ ]:
import pandas as pd
df = pd.read_csv("/content/Supabase Snippet Untitled query.csv")

## 5. Check for missing values

In [ ]:
# Count missing values in each column
print(df.isna().sum())

document_id           0
title                 0
publisher_name        0
jurisdiction_name     0
document_type         0
publication_date      0
effective_date       15
status                0
dtype: int64

In [ ]:
# Show records with a missing effective date

print(df[df["effective_date"].isna()])

    document_id                                              title  \
1          1017                 Key focus areas for 2025 reporting
2          1025  SR 25-4: Frequently Asked Questions Regarding ...
3          1026  OCC Bulletin 2025-31: Bank Secrecy Act/Anti-Mo...
4          1009                    Monthly Report - September 2025
5          1024  Staff Advisory: Registration Framework for For...
6          1029  FDIC Supervisory Approach Regarding the Use of...
11         1021  Circular CSSF 25/893 - Reporting of major ICT-...
12         1015  Instruction No. 2025-I-04 on electronic signat...
13         1022  FINMA Guidance 02/2025 - Risks in the real est...
14         1018    Submission DORA information register - guidance
15         1019  Periodic questionnaire on the prevention of mo...
16         1016     Regulatory and Supervisory Outlook Report 2025
17         1023                      Staff Statement on Meme Coins
18         1001  Circular 02/2025 (A) - Minimum requirements fo...
20         1011     AMF Action and Supervisory Priorities for 2025

             publisher_name jurisdiction_name         document_type  \
1                       AFM       Netherlands              Guidance
2           Federal Reserve     United States    Supervisory Letter
3                       OCC     United States              Bulletin
4       Deutsche Bundesbank           Germany                Report
5                      CFTC     United States              Advisory
6                      FDIC     United States  Supervisory Guidance
11                     CSSF        Luxembourg              Circular
12                     ACPR            France           Instruction
13                    FINMA       Switzerland              Guidance
14    De Nederlandsche Bank       Netherlands              Guidance
15                     FSMA           Belgium              Circular
16  Central Bank of Ireland           Ireland                Report
17                      SEC     United States             Statement
18                    BaFin           Germany              Circular
20                      AMF            France                Report

   publication_date effective_date      status
1        2025-10-24            NaN      Active
2        2025-10-10            NaN      Active
3        2025-10-09            NaN      Active
4        2025-09-18            NaN      Active
5        2025-08-28            NaN  Superseded
6        2025-08-05            NaN      Active
11       2025-05-28            NaN      Active
12       2025-05-22            NaN      Active
13       2025-05-22            NaN      Active
14       2025-04-22            NaN      Active
15       2025-04-01            NaN   Withdrawn
16       2025-02-28            NaN  Superseded
17       2025-02-27            NaN      Active
18       2025-02-12            NaN      Active
20       2025-01-16            NaN      Active

In [ ]:
# Show records where an effective date is available
print(df[df["effective_date"].notna()])

    document_id                                              title  \
0          1030                                 2025 Annual Report
7          1014             FG25/5: Primary Market Bulletin No. 57
8          1013  FG25/4: Amendments to PRA Rulebook and FCA Gui...
9          1012   FG25/3: Treatment of politically exposed persons
10         1020  PS8/25: Updates to the UK policy framework for...
19         1027  Final report on amending Guidelines on ICT ris...
21         1004          SS3/24: Credit risk definition of default
22         1003  SS2/24: Solvent exit planning for non-systemic...
23         1006  Guidelines on policies and controls for the ef...
24         1007  Guidelines on the use of remote customer onboa...
25         1002  FG22/5: Final non-Handbook guidance for firms ...
26         1005               Guidelines on risk-based supervision
27         1028  Guidelines on the MiFID II/MiFIR obligations o...
28         1008  Guidelines on certain aspects of the MiFID II ...
29         1010                Guide to fit and proper assessments

   publisher_name jurisdiction_name          document_type publication_date  \
0            ESMA    European Union          Annual Report       2026-06-17
7             FCA    United Kingdom     Finalised Guidance       2025-07-25
8             FCA    United Kingdom     Finalised Guidance       2025-07-08
9             FCA    United Kingdom     Finalised Guidance       2025-07-07
10            PRA    United Kingdom       Policy Statement       2025-07-03
19            EBA    European Union           Final Report       2025-02-11
21            PRA    United Kingdom  Supervisory Statement       2024-09-12
22            PRA    United Kingdom  Supervisory Statement       2024-03-12
23            EBA    European Union             Guidelines       2023-03-31
24            EBA    European Union             Guidelines       2022-11-22
25            FCA    United Kingdom               Guidance       2022-07-27
26            EBA    European Union             Guidelines       2021-12-16
27           ESMA    European Union             Guidelines       2021-08-18
28           ESMA    European Union             Guidelines       2018-05-03
29            ECB    European Union                  Guide       2018-05-01

   effective_date      status
0      2026-06-17      Active
7      2025-07-25      Active
8      2025-07-08      Active
9      2025-07-07      Active
10     2025-07-03      Active
19     2025-02-11      Active
21     2024-09-12  Superseded
22     2025-10-01      Active
23     2023-11-03      Active
24     2023-10-02      Active
25     2023-07-31      Active
26     2022-07-04      Active
27     2022-01-01   Withdrawn
28     2018-05-03      Active
29     2018-05-01      Active

In [ ]:
# Missing effective dates
df["effective_date"].isna().sum()

np.int64(15)

In [ ]:
# Count missing and available effective dates
missing_effective_dates = df["effective_date"].isna().sum()
available_effective_dates = df["effective_date"].notna().sum()

print("Missing effective dates:", missing_effective_dates)
print("Available effective dates:", available_effective_dates)

Missing effective dates: 15
Available effective dates: 15